meson: explicitly depend on libwayland for includes
On BSDs base compiler doesn't search packages by default, making it
easy for vendors to depend only on base system.

FAILED: wlsunset.p/main.c.o
cc -Iwlsunset.p -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -g -Wundef -Wunused -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Wstrict-prototypes -Wimplicit-fallthrough -Wmissing-prototypes -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wvla -Wl,--exclude-libs=ALL -D_USE_MATH_DEFINES -D_XOPEN_SOURCE=700 -MD -MQ wlsunset.p/main.c.o -MF wlsunset.p/main.c.o.d -o wlsunset.p/main.c.o -c ../main.c
../main.c:14:10: fatal error: 'wayland-client-protocol.h' file not found
 #include <wayland-client-protocol.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.